import Link from "next/link";
import { getServerSession } from "next-auth";
import { redirect } from "next/navigation";

import { authOptions } from "@/lib/auth";
import { prisma } from "@/lib/prisma";
import { tiposSimulacro } from "@/lib/simulacros";

type SearchParams = Promise<{ anio?: string; mes?: string }>;
type Conteo = { programados: number; detectados: number; perdidos: number };
type Actividad = { id: number; origenId: string | null; fechaPlaneada: Date; finca: string; actividad: string };

function partesColombia(fecha = new Date()) { const partes = new Intl.DateTimeFormat("en-CA", { timeZone: "America/Bogota", year: "numeric" }).formatToParts(fecha); return Object.fromEntries(partes.map((parte) => [parte.type, parte.value])); }
function obtenerAnio(valor?: string) { const actual = Number(partesColombia().year); const anio = Number(valor); return Number.isInteger(anio) && anio >= 2020 && anio <= actual + 1 ? anio : actual; }
function obtenerMes(valor?: string) { const mes = Number(valor); return Number.isInteger(mes) && mes >= 1 && mes <= 12 ? mes : null; }
function nombreMes(anio: number, mes: number) { return new Intl.DateTimeFormat("es-CO", { month: "long", timeZone: "America/Bogota" }).format(new Date(Date.UTC(anio, mes - 1, 1, 5))); }
function mesColombia(fecha: Date) { return Number(new Intl.DateTimeFormat("en-CA", { month: "numeric", timeZone: "America/Bogota" }).format(fecha)); }
function etiquetaTipo(tipo: string) { return tipo.replace(/^SIMULACRO\s+/, "").replace("CONTAMINACION", "CONTAMINACIÓN"); }
function esPerdido(resultado: string) { return String(resultado).trim().toUpperCase() === "NO DETECTADO"; }

function estadoSac(sac: { estado: string; actividadReprogramadaId: number | null; fechaReprogramacion: Date | null; fechaCierre: Date | null } | null, requiereSac: boolean, esHistorico: boolean) {
  if (!sac && esHistorico) return { texto: "Histórico importado · SAC gestionada en formato anterior", clase: "bg-sky-100 text-sky-800" };
  if (!sac && !requiereSac) return { texto: "No requiere SAC", clase: "bg-slate-100 text-slate-700" };
  if (!sac) return { texto: "Pendiente SAC y reprogramación", clase: "bg-red-100 text-red-800" };
  if (sac.estado === "CERRADA" || sac.fechaCierre) return { texto: "SAC cerrada tras reprogramación", clase: "bg-green-100 text-green-800" };
  if (sac.actividadReprogramadaId) { const fecha = sac.fechaReprogramacion?.toLocaleDateString("es-CO", { timeZone: "America/Bogota" }); return { texto: `SAC en seguimiento · reprogramada${fecha ? ` para ${fecha}` : ""}`, clase: "bg-amber-100 text-amber-900" }; }
  return { texto: "SAC creada · pendiente reprogramar", clase: "bg-amber-100 text-amber-900" };
}

export default async function MetricasSimulacrosPage({ searchParams }: { searchParams: SearchParams }) {
  const session = await getServerSession(authOptions); const rol = String(session?.user?.role || ""); if (!["ADMIN", "JEFE_SEG", "DIRECTOR_SEG"].includes(rol)) redirect("/dashboard");
  const params = await searchParams; const anio = obtenerAnio(params.anio); const mesFiltro = obtenerMes(params.mes); const inicioAnio = new Date(Date.UTC(anio, 0, 1, 5)); const finAnio = new Date(Date.UTC(anio + 1, 0, 1, 5)); const mesesDetalle = mesFiltro ? [mesFiltro] : Array.from({ length: 12 }, (_, indice) => indice + 1);

  const candidatos = await prisma.actividadSupervisor.findMany({ where: { actividad: { in: [...tiposSimulacro] }, fechaPlaneada: { gte: inicioAnio, lt: finAnio } }, orderBy: [{ finca: "asc" }, { fechaPlaneada: "asc" }, { id: "asc" }], select: { id: true, origenId: true, fechaPlaneada: true, finca: true, actividad: true } });
  const reprogramacionesSac = candidatos.length ? await prisma.solicitudAccion.findMany({ where: { actividadReprogramadaId: { in: candidatos.map((actividad) => actividad.id) } }, select: { actividadReprogramadaId: true } }) : [];
  const idsReprogramadosSac = new Set(reprogramacionesSac.map((sac) => sac.actividadReprogramadaId).filter((id): id is number => id !== null));
  const porFincaCandidatos = candidatos.reduce<Map<string, Actividad[]>>((mapa, actividad) => { const registros = mapa.get(actividad.finca) || []; registros.push(actividad); mapa.set(actividad.finca, registros); return mapa; }, new Map());
  const idsIniciales = new Set<number>(); const idsReprogramados = new Set<number>();
  for (const registros of porFincaCandidatos.values()) {
    const sinMarcaReprogramacion = registros.filter((actividad) => !idsReprogramadosSac.has(actividad.id) && !String(actividad.origenId || "").startsWith("REPROGRAMACION-"));
    sinMarcaReprogramacion.slice(0, 8).forEach((actividad) => idsIniciales.add(actividad.id));
    registros.filter((actividad) => !idsIniciales.has(actividad.id)).forEach((actividad) => idsReprogramados.add(actividad.id));
  }
  const iniciales = candidatos.filter((actividad) => idsIniciales.has(actividad.id));
  const reprogramadosPorFinca = candidatos.reduce<Map<string, number>>((mapa, actividad) => { if (idsReprogramados.has(actividad.id)) mapa.set(actividad.finca, (mapa.get(actividad.finca) || 0) + 1); return mapa; }, new Map());
  const informes = iniciales.length ? await prisma.simulacroActividad.findMany({ where: { actividadId: { in: iniciales.map((actividad) => actividad.id) } }, include: { solicitudAccion: { select: { estado: true, actividadReprogramadaId: true, fechaReprogramacion: true, fechaCierre: true } } } }) : [];
  const inicialPorId = new Map(iniciales.map((actividad) => [actividad.id, actividad])); const informesPorActividad = new Map(informes.map((informe) => [informe.actividadId, informe]));

  const resumenMesTipo = new Map<string, Conteo>(); const resumenFinca = new Map<string, Conteo>();
  for (const finca of porFincaCandidatos.keys()) resumenFinca.set(finca, { programados: 8, detectados: 0, perdidos: 0 });
  for (const actividad of iniciales) {
    const informe = informesPorActividad.get(actividad.id); const acumular = (mapa: Map<string, Conteo>, llave: string, sumaInicial: boolean) => { const conteo = mapa.get(llave) || { programados: 0, detectados: 0, perdidos: 0 }; if (sumaInicial) conteo.programados += 1; if (informe?.resultado === "DETECTADO") conteo.detectados += 1; if (informe && esPerdido(informe.resultado)) conteo.perdidos += 1; mapa.set(llave, conteo); };
    acumular(resumenMesTipo, `${mesColombia(actividad.fechaPlaneada)}-${actividad.actividad}`, true); acumular(resumenFinca, actividad.finca, false);
  }
  const rankingFincas = Array.from(resumenFinca.entries()).map(([finca, conteo]) => ({ finca, ...conteo, reprogramados: reprogramadosPorFinca.get(finca) || 0, porcentajePerdida: Math.round((conteo.perdidos / 8) * 100) })).sort((a, b) => b.perdidos - a.perdidos || b.porcentajePerdida - a.porcentajePerdida || a.finca.localeCompare(b.finca));
  const fincaMasPierde = rankingFincas[0]; const fincaMasAlineada = [...rankingFincas].sort((a, b) => a.porcentajePerdida - b.porcentajePerdida || b.detectados - a.detectados || a.finca.localeCompare(b.finca))[0];
  const perdidosAnuales = informes.filter((informe) => esPerdido(informe.resultado)).map((informe) => ({ informe, actividad: inicialPorId.get(informe.actividadId)! })).sort((a, b) => b.actividad.fechaPlaneada.getTime() - a.actividad.fechaPlaneada.getTime());
  const perdidos = mesFiltro ? perdidosAnuales.filter(({ actividad }) => mesColombia(actividad.fechaPlaneada) === mesFiltro) : perdidosAnuales; const sacPendientes = perdidosAnuales.filter(({ informe }) => informe.requiereSac && !informe.solicitudAccion).length; const sacsEnSeguimiento = perdidosAnuales.filter(({ informe }) => informe.solicitudAccion?.estado === "EN_SEGUIMIENTO").length;
  const etiquetaDetalle = mesFiltro ? `Detalle de ${nombreMes(anio, mesFiltro)} de ${anio}` : `Vista general de ${anio}`;

  return <main className="mx-auto max-w-7xl space-y-6 p-6"><div className="flex flex-wrap items-end justify-between gap-4"><div><h1 className="text-3xl font-bold text-[#0F3D1F]">Métricas de simulacros</h1><p className="mt-1 capitalize text-slate-600">{etiquetaDetalle}. El ranking y la tasa conservan la base anual de 8 simulacros iniciales por finca.</p></div><form action="/simulacros/metricas" className="flex flex-wrap items-end gap-2 rounded-xl border bg-white p-3 shadow-sm"><label className="flex flex-col gap-1 text-sm font-semibold text-slate-700">Año<input name="anio" type="number" min="2020" max={String(Number(partesColombia().year) + 1)} defaultValue={anio} className="w-28 rounded-lg border p-2 font-normal" /></label><label className="flex flex-col gap-1 text-sm font-semibold text-slate-700">Mes<select name="mes" defaultValue={mesFiltro ? String(mesFiltro) : ""} className="rounded-lg border p-2 font-normal"><option value="">Todo el año</option>{Array.from({ length: 12 }, (_, indice) => indice + 1).map((mes) => <option key={mes} value={mes} className="capitalize">{nombreMes(anio, mes)}</option>)}</select></label><button className="rounded-lg bg-[#0F3D1F] px-4 py-2 font-semibold text-white">Ver métricas</button></form></div>
    <section className="grid gap-4 md:grid-cols-2 xl:grid-cols-5"><Tarjeta etiqueta="Iniciales esperados" valor={rankingFincas.length * 8} /><Tarjeta etiqueta="Informes iniciales" valor={informes.length} color="text-[#0F3D1F]" /><Tarjeta etiqueta="Detectados iniciales" valor={informes.filter((informe) => informe.resultado === "DETECTADO").length} color="text-green-700" /><Tarjeta etiqueta="Perdidos iniciales" valor={perdidosAnuales.length} color="text-red-700" /><Tarjeta etiqueta="SAC pendientes vigentes" valor={sacPendientes} color="text-red-700" /></section>
    <section className="rounded-xl border border-sky-200 bg-sky-50 p-4 text-sm text-sky-900"><strong>Regla del indicador:</strong> cada finca tiene una base de 8 simulacros iniciales anuales (4 tipos, uno por semestre). Todo registro adicional se clasifica como reprogramación y queda excluido de los perdidos y de la tasa de pérdida.</section>
    <section className="rounded-xl border bg-white p-5 shadow-sm"><h2 className="text-xl font-bold text-[#0F3D1F]">Cumplimiento por mes y tipo de simulacro</h2><p className="mt-1 text-sm text-slate-500">Cada fila muestra: <strong>iniciales registrados / detectados iniciales / perdidos iniciales</strong>.</p><div className="mt-5 overflow-x-auto"><table className="min-w-full text-sm"><thead className="border-b bg-slate-50 text-left"><tr><th className="p-3">Mes</th><th className="p-3">Tipo</th><th className="p-3 text-center">Iniciales</th><th className="p-3 text-center">Detectados</th><th className="p-3 text-center">Perdidos</th></tr></thead><tbody>{mesesDetalle.flatMap((mes) => [...tiposSimulacro].map((tipo, indice) => { const conteo = resumenMesTipo.get(`${mes}-${tipo}`) || { programados: 0, detectados: 0, perdidos: 0 }; return <tr key={`${mes}-${tipo}`} className="border-b last:border-0"><td className="p-3 capitalize">{indice === 0 ? nombreMes(anio, mes) : ""}</td><td className="p-3 font-medium">{etiquetaTipo(tipo)}</td><td className="p-3 text-center">{conteo.programados}</td><td className="p-3 text-center font-bold text-green-700">{conteo.detectados}</td><td className="p-3 text-center font-bold text-red-700">{conteo.perdidos}</td></tr>; }))}</tbody></table></div></section>
    <div className="grid gap-6 xl:grid-cols-2"><section className="rounded-xl border bg-white p-5 shadow-sm"><h2 className="text-xl font-bold text-[#0F3D1F]">Ranking de fincas</h2><p className="mt-1 text-sm text-slate-500">Tasa de pérdida = simulacros iniciales perdidos ÷ 8. Las reprogramaciones se muestran separadas y no influyen en la tasa.</p><div className="mt-5 overflow-x-auto"><table className="min-w-full text-sm"><thead className="border-b bg-slate-50 text-left"><tr><th className="p-3">Finca</th><th className="p-3 text-center">Iniciales</th><th className="p-3 text-center">Reprogramados</th><th className="p-3 text-center">Detectados</th><th className="p-3 text-center">Perdidos</th><th className="p-3 text-center">Tasa pérdida</th></tr></thead><tbody>{rankingFincas.map((fila) => <tr key={fila.finca} className="border-b last:border-0"><td className="p-3 font-semibold">{fila.finca}</td><td className="p-3 text-center">8</td><td className="p-3 text-center text-amber-800">{fila.reprogramados}</td><td className="p-3 text-center text-green-700">{fila.detectados}</td><td className="p-3 text-center font-bold text-red-700">{fila.perdidos}</td><td className="p-3 text-center">{fila.porcentajePerdida}%</td></tr>)}{rankingFincas.length === 0 && <tr><td colSpan={6} className="p-5 text-center text-slate-500">No hay simulacros registrados en {anio}.</td></tr>}</tbody></table></div></section><section className="space-y-4 rounded-xl border bg-white p-5 shadow-sm"><h2 className="text-xl font-bold text-[#0F3D1F]">Lectura de resultados anual</h2><Indicador titulo="Finca con más pérdidas iniciales" valor={fincaMasPierde ? `${fincaMasPierde.finca} · ${fincaMasPierde.perdidos} perdido(s)` : "Sin datos"} clase="border-red-200 bg-red-50 text-red-900" /><Indicador titulo="Finca más alineada con Seguridad" valor={fincaMasAlineada ? `${fincaMasAlineada.finca} · ${fincaMasAlineada.porcentajePerdida}% de pérdida` : "Sin datos"} clase="border-green-200 bg-green-50 text-green-900" /><Indicador titulo="SAC en seguimiento" valor={`${sacsEnSeguimiento} SAC`} clase="border-amber-200 bg-amber-50 text-amber-900" /><p className="text-xs text-slate-500">Esta lectura siempre usa el año completo seleccionado y no varía al filtrar el detalle por mes.</p></section></div>
    <section className="rounded-xl border bg-white p-5 shadow-sm"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-xl font-bold text-[#0F3D1F]">Simulacros iniciales perdidos y trazabilidad de la SAC</h2><p className="mt-1 text-sm text-slate-500">Los históricos importados muestran que su SAC fue gestionada en el formato anterior.</p></div><Link href="/simulacros" className="rounded border px-4 py-2 font-semibold">Ver simulacros</Link></div><div className="mt-5 overflow-x-auto"><table className="min-w-full text-sm"><thead className="border-b bg-slate-50 text-left"><tr><th className="p-3">Fecha</th><th className="p-3">Finca</th><th className="p-3">Tipo</th><th className="p-3">Consecutivo</th><th className="p-3">Estado SAC / reprogramación</th><th className="p-3">Acción</th></tr></thead><tbody>{perdidos.map(({ informe, actividad }) => { const estado = estadoSac(informe.solicitudAccion, informe.requiereSac, informe.creadoPorCorreo === "historico@falconservice.local"); return <tr key={informe.id} className="border-b last:border-0"><td className="p-3">{actividad.fechaPlaneada.toLocaleDateString("es-CO", { timeZone: "America/Bogota" })}</td><td className="p-3 font-semibold">{actividad.finca}</td><td className="p-3">{etiquetaTipo(informe.tipo)}</td><td className="p-3">{informe.consecutivo || `SIM-${informe.id}`}</td><td className="p-3"><span className={`inline-block rounded px-2 py-1 text-xs font-bold ${estado.clase}`}>{estado.texto}</span></td><td className="p-3"><Link href={`/simulacros/${informe.id}`} className="font-semibold text-[#0F3D1F] underline">Ver detalle</Link></td></tr>; })}{perdidos.length === 0 && <tr><td colSpan={6} className="p-5 text-center text-slate-500">No hay simulacros iniciales perdidos en este detalle.</td></tr>}</tbody></table></div></section>
  </main>;
}

function Tarjeta({ etiqueta, valor, color = "text-slate-900" }: { etiqueta: string; valor: number; color?: string }) { return <article className="rounded-xl border bg-white p-5 shadow-sm"><p className="text-sm text-slate-500">{etiqueta}</p><p className={`mt-1 text-3xl font-bold ${color}`}>{valor}</p></article>; }
function Indicador({ titulo, valor, clase }: { titulo: string; valor: string; clase: string }) { return <article className={`rounded-xl border p-4 ${clase}`}><p className="text-sm font-semibold">{titulo}</p><p className="mt-1 text-lg font-bold">{valor}</p></article>; }
