"use client";

import { useMemo, useState } from "react";
import Link from "next/link";
import toast from "react-hot-toast";
import UploadButton from "@/components/uploadthing/UploadButton";

type Archivo = { nombre: string; url: string; tipo?: string };
type Paso = { descripcion: string };

function horaDistribuida(inicio: string, duracion: number, indice: number, total: number) {
  if (!inicio) return "--:--";
  const [hora, minuto] = inicio.split(":").map(Number);
  const totalMinutos = (hora * 60 + minuto + (total <= 1 ? 0 : Math.round((duracion * indice) / (total - 1)))) % 1440;
  return `${String(Math.floor(totalMinutos / 60)).padStart(2, "0")}:${String(totalMinutos % 60).padStart(2, "0")}`;
}

export default function FormularioSimulacro({ actividad, definicion, personasInformadasInicial }: { actividad: { id: number; finca: string; area: string | null; actividad: string; supervisorNombre: string | null }; definicion: { analista: string; objetivo: string; riesgo: string; controles: string[]; guionInicial: string; aspectos: string[] }; personasInformadasInicial: string }) {
  const [horaInicio, setHoraInicio] = useState(""); const [duracionMinutos, setDuracionMinutos] = useState(""); const [resultado, setResultado] = useState(""); const [cumplimientoObjetivo, setCumplimientoObjetivo] = useState("");
  const [grupoObjeto, setGrupoObjeto] = useState(""); const [escenario, setEscenario] = useState("");
  const [pasos, setPasos] = useState<Paso[]>([{ descripcion: "Por parte del coordinador del simulacro se explica la ejecución de la actividad y su alcance, según el guion establecido." }, { descripcion: definicion.guionInicial }]);
  const [conclusion, setConclusion] = useState(""); const [controlVulnerado, setControlVulnerado] = useState(""); const [razonIncumplimiento, setRazonIncumplimiento] = useState(""); const [factoresFalla, setFactoresFalla] = useState<string[]>([]); const [evidencias, setEvidencias] = useState<Archivo[]>([]); const [guardando, setGuardando] = useState(false);
  const [aspectos, setAspectos] = useState(definicion.aspectos.map((nombre) => ({ nombre, calificacion: "" })));
  const promedio = useMemo(() => { const puntos = { 3: 1, 2: 0.5, 1: 0 }; const valores = aspectos.map((item) => puntos[Number(item.calificacion) as 1 | 2 | 3]).filter((v) => v !== undefined); return valores.length === aspectos.length && valores.length ? valores.reduce((a, b) => a + b, 0) / valores.length : null; }, [aspectos]);
  const requiereSac = resultado === "NO DETECTADO" || (promedio !== null && promedio <= 0.5);
  const desarrollo = pasos.map((paso, indice) => `${horaDistribuida(horaInicio, Number(duracionMinutos) || 0, indice, pasos.length)} - ${paso.descripcion.trim()}`).join("\n\n");
  const agregarPaso = () => setPasos((actual) => [...actual, { descripcion: "" }]);

  async function guardar() {
    setGuardando(true);
    try {
      const respuesta = await fetch(`/api/actividades-supervisores/${actividad.id}/simulacro`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ horaInicio, duracionMinutos: Number(duracionMinutos), grupoObjeto, escenario, resultado, cumplimientoObjetivo, desarrollo, pasos, aspectos, conclusion, controlVulnerado, razonIncumplimiento, factoresFalla, evidencias }) });
      const data = await respuesta.json(); if (!respuesta.ok) throw new Error(data.error || "No fue posible guardar el simulacro");
      toast.success(data.requiereSac ? "Simulacro cerrado. Se generó una SAC sugerida para el Analista SIG." : "Simulacro cerrado y notificado correctamente."); window.location.href = `/actividades-supervisores/${actividad.id}/simulacro`;
    } catch (error: any) { toast.error(error.message || "No fue posible guardar el simulacro"); } finally { setGuardando(false); }
  }

  return <div className="mx-auto max-w-4xl space-y-5">
    <div className="flex items-start justify-between gap-4"><div><h1 className="text-3xl font-bold text-[#0F3D1F]">Formulario de simulacro</h1><p className="mt-1 text-slate-600">{actividad.actividad} · {actividad.finca} · {actividad.area || "Sin área"}</p></div><Link href={`/actividades-supervisores/${actividad.id}`} className="rounded-lg border bg-white px-4 py-2 font-semibold">Volver</Link></div>
    <section className="rounded-xl border bg-white p-5 shadow-sm"><h2 className="text-xl font-bold text-[#0F3D1F]">Planeación del simulacro</h2><div className="mt-3 grid gap-3 text-sm md:grid-cols-2"><p><strong>Coordinador:</strong> {actividad.supervisorNombre}</p><p><strong>Analista SIG coordinado:</strong> {definicion.analista}</p><p><strong>Riesgo:</strong> {definicion.riesgo}</p><p><strong>Controles:</strong> {definicion.controles.join(", ")}</p></div><p className="mt-4 text-sm"><strong>Objetivo:</strong> {definicion.objetivo}</p><div className="mt-4 grid gap-3 md:grid-cols-2"><label className="font-semibold">Grupo objeto del simulacro<input value={grupoObjeto} onChange={(e) => setGrupoObjeto(e.target.value)} className="mt-1 w-full rounded border p-3 font-normal" placeholder={`Personal de ${actividad.finca}`} /></label><div><p className="font-semibold">Personas y cargos informados</p><p className="mt-1 min-h-20 rounded border bg-slate-50 p-3 text-sm">{personasInformadasInicial}</p></div><label className="font-semibold md:col-span-2">Escenario<textarea value={escenario} onChange={(e) => setEscenario(e.target.value)} className="mt-1 min-h-20 w-full rounded border p-3 font-normal" placeholder={`Área de ${actividad.area || "la finca"}`} /></label></div></section>
    <section className="space-y-4 rounded-xl border bg-white p-5 shadow-sm"><h2 className="text-xl font-bold text-[#0F3D1F]">Resultados y evaluación</h2><div className="grid gap-4 md:grid-cols-3"><label className="font-semibold">Hora de inicio<input type="time" value={horaInicio} onChange={(e) => setHoraInicio(e.target.value)} className="mt-1 w-full rounded border p-3 font-normal" /></label><label className="font-semibold">Duración de ejecución (minutos)<input type="number" min="1" value={duracionMinutos} onChange={(e) => setDuracionMinutos(e.target.value)} className="mt-1 w-full rounded border p-3 font-normal" /></label><label className="font-semibold">Resultado<select value={resultado} onChange={(e) => setResultado(e.target.value)} className="mt-1 w-full rounded border p-3 font-normal"><option value="">Seleccione</option><option value="DETECTADO">Detectado</option><option value="NO DETECTADO">No detectado / perdido</option></select></label></div><label className="block font-semibold">Cumplimiento del objetivo<textarea value={cumplimientoObjetivo} onChange={(e) => setCumplimientoObjetivo(e.target.value)} className="mt-1 min-h-24 w-full rounded border p-3 font-normal" /></label>
      <div><p className="font-semibold">Pasos del desarrollo</p><p className="mt-1 text-sm text-slate-500">Escriba cada evento. Presione Enter en el último paso o use “Agregar paso”; las horas se distribuyen dentro de la duración indicada.</p><div className="mt-3 space-y-2">{pasos.map((paso, indice) => <div key={indice} className="flex gap-2"><span className="w-16 rounded border bg-slate-50 p-3 text-center text-sm font-semibold">{horaDistribuida(horaInicio, Number(duracionMinutos) || 0, indice, pasos.length)}</span><textarea value={paso.descripcion} onChange={(e) => setPasos((actual) => actual.map((item, i) => i === indice ? { descripcion: e.target.value } : item))} onKeyDown={(e) => { if (e.key === "Enter" && !e.shiftKey && indice === pasos.length - 1) { e.preventDefault(); agregarPaso(); } }} className="min-h-16 flex-1 rounded border p-3" placeholder="Describa este paso" />{pasos.length > 1 && <button type="button" onClick={() => setPasos((actual) => actual.filter((_, i) => i !== indice))} className="rounded border px-3 text-red-700">Quitar</button>}</div>)}</div><button type="button" onClick={agregarPaso} className="mt-3 rounded border px-4 py-2 font-semibold">+ Agregar paso</button></div>
      <label className="block font-semibold">Desarrollo del simulacro generado<textarea readOnly value={desarrollo} className="mt-1 min-h-48 w-full rounded border bg-slate-50 p-3 font-normal" /></label>
      <div><p className="font-semibold">Aspectos a evaluar <span className="font-normal">(Excelente: 1 punto · Bueno: 0,5 puntos · Deficiente: 0 puntos)</span></p><div className="mt-2 space-y-2">{aspectos.map((aspecto, indice) => <label key={aspecto.nombre} className="flex items-center justify-between gap-3 rounded border p-3 text-sm"><span>{aspecto.nombre}</span><select value={aspecto.calificacion} onChange={(e) => setAspectos((actual) => actual.map((item, i) => i === indice ? { ...item, calificacion: e.target.value } : item))} className="rounded border p-2"><option value="">Califique</option><option value="3">Excelente · 1 punto</option><option value="2">Bueno · 0,5 puntos</option><option value="1">Deficiente · 0 puntos</option></select></label>)}</div>{promedio !== null && <p className="mt-3 font-semibold">Promedio de evaluación: {promedio.toFixed(2)} / 1 ({Math.round(promedio * 100)}%)</p>}</div>
      <label className="block font-semibold">Conclusión general<textarea value={conclusion} onChange={(e) => setConclusion(e.target.value)} className="mt-1 min-h-28 w-full rounded border p-3 font-normal" /></label><label className="block font-semibold">Control vulnerado (si aplica)<input value={controlVulnerado} onChange={(e) => setControlVulnerado(e.target.value)} className="mt-1 w-full rounded border p-3 font-normal" /></label>{requiereSac && <div className="rounded-lg border border-red-200 bg-red-50 p-4"><p className="font-semibold text-red-900">Se generará una SAC sugerida por resultado no detectado o promedio igual o inferior a 0,5 (50%).</p><label className="mt-3 block font-semibold">Razón del incumplimiento<textarea value={razonIncumplimiento} onChange={(e) => setRazonIncumplimiento(e.target.value)} className="mt-1 min-h-24 w-full rounded border p-3 font-normal" /></label><p className="mt-3 font-semibold">Factores identificados</p>{["Capacitación y competencia", "Roles y responsabilidades", "Estandarización", "Recursos", "Aseguramiento", "Factor externo"].map((factor) => <label key={factor} className="mt-1 flex gap-2 text-sm"><input type="checkbox" checked={factoresFalla.includes(factor)} onChange={(e) => setFactoresFalla((actual) => e.target.checked ? [...actual, factor] : actual.filter((item) => item !== factor))} />{factor}</label>)}</div>}<div><p className="font-semibold">Evidencias fotográficas o PDF</p><div className="mt-2"><UploadButton allowedExtensions={["jpg", "jpeg", "png", "webp", "pdf"]} allowedExtensionsLabel="imágenes o PDF" onCompleteMany={(archivos: Archivo[]) => setEvidencias((actual) => [...actual, ...archivos])} /></div>{evidencias.map((archivo) => <p key={archivo.url} className="mt-2 rounded bg-slate-50 p-2 text-sm">{archivo.nombre}</p>)}</div><button disabled={guardando} onClick={guardar} className="rounded-lg bg-[#0F3D1F] px-5 py-3 font-semibold text-white disabled:bg-slate-400">{guardando ? "Guardando..." : "Cerrar simulacro y generar informe"}</button></section>
  </div>;
}
