"use client";

import { useState } from "react";
import toast from "react-hot-toast";

export default function GestionSimulacro({ simulacro, puedeEditar, puedeEliminar }: { simulacro: { id: number; resultado: string; cumplimientoObjetivo: string; desarrollo: string; conclusion: string; controlVulnerado: string | null; razonIncumplimiento: string | null }; puedeEditar: boolean; puedeEliminar: boolean }) {
  const [editando, setEditando] = useState(false);
  const [datos, setDatos] = useState(simulacro);
  const [guardando, setGuardando] = useState(false);
  async function guardar() { setGuardando(true); try { const respuesta = await fetch(`/api/simulacros/${simulacro.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(datos) }); const data = await respuesta.json(); if (!respuesta.ok) throw new Error(data.error || "No fue posible editar"); toast.success("Simulacro actualizado"); setEditando(false); window.location.reload(); } catch (error: any) { toast.error(error.message); } finally { setGuardando(false); } }
  async function eliminar() { if (!window.confirm("¿Eliminar este simulacro y su SAC asociada? Esta acción no se puede deshacer.")) return; const respuesta = await fetch(`/api/simulacros/${simulacro.id}`, { method: "DELETE" }); const data = await respuesta.json(); if (!respuesta.ok) return toast.error(data.error || "No fue posible eliminar"); toast.success("Simulacro eliminado"); window.location.href = "/simulacros"; }
  if (!puedeEditar && !puedeEliminar) return null;
  return <div className="mt-5 flex flex-wrap gap-3">{puedeEditar && <button onClick={() => setEditando((actual) => !actual)} className="rounded bg-amber-500 px-4 py-2 font-semibold text-white">{editando ? "Cancelar edición" : "Editar simulacro"}</button>}{puedeEliminar && <button onClick={eliminar} className="rounded bg-red-600 px-4 py-2 font-semibold text-white">Eliminar simulacro</button>}{editando && <section className="w-full space-y-3 rounded-xl border bg-amber-50 p-4"><h2 className="text-lg font-bold">Editar información registrada</h2><label className="block font-semibold">Resultado<select value={datos.resultado} onChange={(e) => setDatos({ ...datos, resultado: e.target.value })} className="mt-1 w-full rounded border p-2"><option value="DETECTADO">Detectado</option><option value="NO DETECTADO">No detectado</option></select></label><label className="block font-semibold">Cumplimiento del objetivo<textarea value={datos.cumplimientoObjetivo} onChange={(e) => setDatos({ ...datos, cumplimientoObjetivo: e.target.value })} className="mt-1 min-h-20 w-full rounded border p-2" /></label><label className="block font-semibold">Desarrollo<textarea value={datos.desarrollo} onChange={(e) => setDatos({ ...datos, desarrollo: e.target.value })} className="mt-1 min-h-48 w-full rounded border p-2" /></label><label className="block font-semibold">Conclusión<textarea value={datos.conclusion} onChange={(e) => setDatos({ ...datos, conclusion: e.target.value })} className="mt-1 min-h-24 w-full rounded border p-2" /></label><label className="block font-semibold">Control vulnerado<input value={datos.controlVulnerado || ""} onChange={(e) => setDatos({ ...datos, controlVulnerado: e.target.value })} className="mt-1 w-full rounded border p-2" /></label><label className="block font-semibold">Razón de incumplimiento<textarea value={datos.razonIncumplimiento || ""} onChange={(e) => setDatos({ ...datos, razonIncumplimiento: e.target.value })} className="mt-1 min-h-20 w-full rounded border p-2" /></label><button disabled={guardando} onClick={guardar} className="rounded bg-[#0F3D1F] px-4 py-2 font-semibold text-white">{guardando ? "Guardando..." : "Guardar cambios"}</button></section>}</div>;
}
