type Fila = { finca: string; ingreso: number; mantenimiento: number; confiable: number; noConfiable: number };

function Grafica({ titulo, filas, primera, segunda, colorPrimero, colorSegundo }: { titulo: string; filas: Fila[]; primera: keyof Fila; segunda: keyof Fila; colorPrimero: string; colorSegundo: string }) {
  const maximo = Math.max(1, ...filas.map((fila) => Number(fila[primera]) + Number(fila[segunda])));
  return <section className="rounded-xl border bg-slate-950 p-5 text-white"><div className="flex flex-wrap items-center justify-between gap-3"><h3 className="font-bold uppercase">{titulo}</h3><div className="flex gap-3 text-xs"><span><i className={`mr-1 inline-block h-2.5 w-2.5 rounded-full ${colorPrimero}`} />{primera === "ingreso" ? "Ingreso" : "Confiable"}</span><span><i className={`mr-1 inline-block h-2.5 w-2.5 rounded-full ${colorSegundo}`} />{segunda === "mantenimiento" ? "Mantenimiento" : "No confiable"}</span></div></div>{filas.length === 0 ? <p className="mt-5 text-sm text-slate-300">No hay visitas registradas durante el mes en curso.</p> : <><div className="mt-5 flex min-h-52 items-end gap-3 overflow-x-auto border-b border-slate-600 pb-2">{filas.map((fila) => { const uno = Number(fila[primera]); const dos = Number(fila[segunda]); return <div key={fila.finca} className="flex min-w-16 flex-1 flex-col items-center gap-2"><div className="flex h-40 items-end gap-1"><div title={`${primera}: ${uno}`} className={`flex w-6 items-start justify-center rounded-t pt-1 text-xs font-bold text-white ${colorPrimero}`} style={{ height: `${uno ? Math.max(12, (uno / maximo) * 100) : 0}%` }}>{uno || ""}</div><div title={`${segunda}: ${dos}`} className={`flex w-6 items-start justify-center rounded-t pt-1 text-xs font-bold text-white ${colorSegundo}`} style={{ height: `${dos ? Math.max(12, (dos / maximo) * 100) : 0}%` }}>{dos || ""}</div></div><span className="max-w-20 text-center text-xs font-semibold text-slate-200">{fila.finca}</span></div>; })}</div><div className="mt-4 overflow-x-auto"><table className="min-w-full text-xs"><thead className="text-slate-300"><tr><th className="p-2 text-left">Finca</th><th className="p-2 text-right">{primera === "ingreso" ? "Ingreso" : "Confiable"}</th><th className="p-2 text-right">{segunda === "mantenimiento" ? "Mantenimiento" : "No confiable"}</th><th className="p-2 text-right">Total</th></tr></thead><tbody>{filas.map((fila) => <tr key={fila.finca} className="border-t border-slate-700"><td className="p-2">{fila.finca}</td><td className="p-2 text-right">{Number(fila[primera])}</td><td className="p-2 text-right">{Number(fila[segunda])}</td><td className="p-2 text-right font-bold">{Number(fila[primera]) + Number(fila[segunda])}</td></tr>)}</tbody></table></div></>}</section>;
}

export default function MetricasVisitasFinca({ filas }: { filas: Fila[] }) {
  return <div className="mt-5 grid gap-5 xl:grid-cols-2"><Grafica titulo="Visitas por finca y tipo" filas={filas.filter((fila) => fila.ingreso || fila.mantenimiento)} primera="ingreso" segunda="mantenimiento" colorPrimero="bg-blue-500" colorSegundo="bg-red-500" /><Grafica titulo="Concepto de la visita domiciliaria" filas={filas.filter((fila) => fila.confiable || fila.noConfiable)} primera="confiable" segunda="noConfiable" colorPrimero="bg-blue-500" colorSegundo="bg-red-500" /></div>;
}
