CREATE TABLE "CatalogoActividad" (
  "id" SERIAL NOT NULL,
  "tipo" TEXT NOT NULL,
  "valor" TEXT NOT NULL,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "CatalogoActividad_pkey" PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "CatalogoActividad_tipo_valor_key" ON "CatalogoActividad"("tipo", "valor");
CREATE INDEX "CatalogoActividad_tipo_idx" ON "CatalogoActividad"("tipo");
INSERT INTO "CatalogoActividad" ("tipo", "valor") VALUES
('FINCA','AJ'),('FINCA','GB'),('FINCA','SZ'),('FINCA','AB'),('FINCA','LN'),('FINCA','TM'),('FINCA','LC'),('FINCA','IB'),('FINCA','I4'),('FINCA','LV'),('FINCA','ADM'),('FINCA','FPK'),('FINCA','CORONEL SIZA'),('FINCA','CARLOS BOSHELL'),('FINCA','FISCAL PTE PIEDRA'),('FINCA','FISIOS'),('FINCA','P0'),
('ACTIVIDAD','SIMULACRO CONTAMINACION'),('ACTIVIDAD','SIMULACRO HURTO'),('ACTIVIDAD','SIMULACRO PAQUETE SOSPECHOSO'),('ACTIVIDAD','SIMULACRO INTRUSION'),('ACTIVIDAD','PRUEBAS ALCOHOLIMETRIA'),('ACTIVIDAD','INSPECCION PUESTRO DE TRABAJO'),('ACTIVIDAD','ESTUDIO DE SEGURIDAD'),('ACTIVIDAD','INVENTARIO DE LLLAVES'),('ACTIVIDAD','ACTAS COMUNICACIONES'),('ACTIVIDAD','ACTAS CANINOS'),('ACTIVIDAD','ACTAS ARMAMENTO'),('ACTIVIDAD','CAMBIO FORRO CHALECO'),('ACTIVIDAD','HORAS EXTRAS 1RA QUINCENA'),('ACTIVIDAD','HORAS EXTRAS 2DA QUINCENA'),('ACTIVIDAD','ASEO ARMAMENTO'),('ACTIVIDAD','ACTA ELEMENTOS DE OFICINA'),('ACTIVIDAD','ENTREGAR FLOR'),('ACTIVIDAD','RECOGER EFECTIVO'),('ACTIVIDAD','VERIFICACIÓN DESPACHOS'),
('AREA','POSCOSECHA'),('AREA','INGRESO PERSONAL'),('AREA','PRODUCCION'),('AREA','SG-SST'),('AREA','ADMINISTRACION'),('AREA','MIPE'),('AREA','MIRFE'),('AREA','MANTENIMIENTO'),('AREA','ALMACEN'),('AREA','CONTRATISTAS'),('AREA','FINCAS'),('AREA','FINCAS OCCIDENTE'),('AREA','FINCAS NORTE'),('AREA','OFICINA GB'),('AREA','CUARTO FRIO DE RECEPCIÓN'),('AREA','LOCKERS'),('AREA','CASA'),('AREA','CONSULTORIO');
