import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();
type Tipo = "SIMULACRO HURTO" | "SIMULACRO INTRUSION" | "SIMULACRO PAQUETE SOSPECHOSO";
type Aspecto = { nombre: string; calificacion: number };
type Registro = { consecutivo: string; fecha: Date; tipo: Tipo; area: string; horaInicio: string; supervisor: string; resultado: "DETECTADO" | "NO DETECTADO"; aspectos: Aspecto[]; conclusion: string; desarrollo: string; reprogramar?: true };
const aspectos = (nombres: string[], valores: number[]) => nombres.map((nombre, indice) => ({ nombre, calificacion: valores[indice] }));
const hurto = (valores: number[]) => aspectos(["Reporte de actividades sospechosas", "Controles de acceso", "Identificación de personas mediante el carné", "Cultura de seguridad", "Activación del plan de emergencia para los riesgos asociados"], valores);
const intrusion = hurto;
const paquete = (valores: number[]) => aspectos(["Reporte de actividades subestándar y detección temprana de paquetes sospechosos", "Plan de contingencia", "Cultura de seguridad", "Aseguramiento del área", "Activación del plan de emergencia para los riesgos asociados"], valores);
const registros: Registro[] = [
  { consecutivo: "SIM-I4-2026-001", fecha: new Date("2026-01-20T14:00:00.000Z"), tipo: "SIMULACRO HURTO", area: "ALMACÉN", horaInicio: "09:00", supervisor: "Cristian Salgado", resultado: "NO DETECTADO", aspectos: hurto([1, 1, 1, 1, 1]), conclusion: "El almacén permanecía abierto, sin controles de acceso, registro de entradas ni cámaras activas. Requiere reprogramación.", desarrollo: "Simulacro histórico importado desde I4 2601. Se identificó riesgo alto de pérdida de activos y necesidad de capacitar al personal.", reprogramar: true },
  { consecutivo: "SIM-I4-2026-002", fecha: new Date("2026-02-09T14:00:00.000Z"), tipo: "SIMULACRO PAQUETE SOSPECHOSO", area: "OFICINA DEL DIRECTOR DE POSCOSECHA", horaInicio: "09:00", supervisor: "Sebastian Yunda Rodriguez", resultado: "DETECTADO", aspectos: paquete([3, 3, 3, 3, 3]), conclusion: "Se registró la ejecución histórica del simulacro de paquete sospechoso y la retroalimentación sobre procedimientos de inspección.", desarrollo: "Simulacro histórico importado desde I4 2602. El paquete fue detectado y reportado durante el ejercicio." },
  { consecutivo: "SIM-I4-2026-003", fecha: new Date("2026-03-10T16:00:00.000Z"), tipo: "SIMULACRO INTRUSION", area: "OFICINAS DE PLANEACIÓN", horaInicio: "11:00", supervisor: "Javier Serna Vargas", resultado: "NO DETECTADO", aspectos: intrusion([1, 1, 1, 1, 1]), conclusion: "El personal de planeación no tenía claro el procedimiento de control de acceso e identificación de personas sospechosas. Requiere reprogramación.", desarrollo: "Simulacro histórico importado desde I4 2603. Se requiere fortalecer identificación y control de ingreso.", reprogramar: true },
  { consecutivo: "SIM-I4-2026-004", fecha: new Date("2026-05-27T11:00:00.000Z"), tipo: "SIMULACRO PAQUETE SOSPECHOSO", area: "OFICINA DE PLANEACIÓN", horaInicio: "06:00", supervisor: "Cristian Salgado", resultado: "NO DETECTADO", aspectos: paquete([1, 1, 1, 1, 1]), conclusion: "El personal no tenía claro el manejo de correspondencia ni la procedencia de la caja abandonada. Requiere reprogramación.", desarrollo: "Simulacro histórico importado desde I4 2604. Se requiere reforzar inspección, sensibilización, control y detección de paquetes sospechosos.", reprogramar: true },
];
function promedio(items: Aspecto[]) { const puntos: Record<number, number> = { 3: 1, 2: 0.5, 1: 0 }; return items.reduce((total, item) => total + puntos[item.calificacion], 0) / items.length; }
async function main() { let importados = 0; let reprogramaciones = 0; for (const registro of registros) { if (await prisma.simulacroActividad.findUnique({ where: { consecutivo: registro.consecutivo }, select: { id: true } })) continue; const origenId = `HISTORICO-${registro.consecutivo}`; if (await prisma.actividadSupervisor.findUnique({ where: { origenId }, select: { id: true } })) continue; await prisma.$transaction(async (tx) => { const actividad = await tx.actividadSupervisor.create({ data: { origenId, fechaPlaneada: registro.fecha, finca: "I4", actividad: registro.tipo, area: registro.area, supervisorNombre: registro.supervisor, estado: "TERMINADO", fechaCierre: registro.fecha, cumplidaEnFecha: true, cerradoPor: registro.supervisor, observacionesCierre: registro.reprogramar ? "Pendiente de reprogramar: no existe una ejecución posterior exitosa del mismo tipo." : "Histórico cerrado por procedimiento anterior.", creadoPor: "Importación histórica", creadoPorCorreo: "historico@falconservice.local", createdAt: registro.fecha } }); await tx.simulacroActividad.create({ data: { actividadId: actividad.id, tipo: registro.tipo, finca: "I4", area: registro.area, grupoObjeto: `Personal de ${registro.area}`, personasInformadas: "Registro histórico importado", escenario: registro.area, horaInicio: registro.horaInicio, duracionMinutos: 30, consecutivo: registro.consecutivo, guion: "Registro histórico importado desde los formatos de simulacro I4 2026.", resultado: registro.resultado, cumplimientoObjetivo: registro.conclusion, desarrollo: registro.desarrollo, pasos: [{ descripcion: registro.desarrollo }], aspectos: registro.aspectos, promedioEvaluacion: promedio(registro.aspectos), conclusion: registro.conclusion, requiereSac: false, evidencias: [], creadoPor: registro.supervisor, creadoPorCorreo: "historico@falconservice.local", createdAt: registro.fecha } }); if (registro.reprogramar) await tx.actividadSupervisor.create({ data: { origenId: `REPROGRAMACION-${registro.consecutivo}`, fechaPlaneada: new Date(), finca: "I4", actividad: registro.tipo, area: registro.area, estado: "PENDIENTE_ASIGNAR", observacionesCierre: `Reprogramación pendiente por resultado no detectado en ${registro.consecutivo}.`, creadoPor: "Importación histórica", creadoPorCorreo: "historico@falconservice.local" } }); }); importados++; if (registro.reprogramar) reprogramaciones++; } console.log(JSON.stringify({ total: registros.length, importados, reprogramaciones })); }
main().finally(() => prisma.$disconnect());
