import { PrismaClient } from "@prisma/client";
const prisma = new PrismaClient();
type Tipo = "SIMULACRO HURTO" | "SIMULACRO INTRUSION" | "SIMULACRO PAQUETE SOSPECHOSO";
type Aspecto = { nombre: string; calificacion: number };
type Registro = { consecutivo: string; fecha: Date; tipo: Tipo; area: string; horaInicio: string; supervisor: string; resultado: "DETECTADO" | "NO DETECTADO"; aspectos: Aspecto[]; conclusion: string; cierrePosterior?: string };
const crear = (n: string[], v: number[]) => n.map((nombre, i) => ({ nombre, calificacion: v[i] }));
const hurto = (v: number[]) => crear(["Reporte de actividades sospechosas", "Controles de acceso", "Identificación de personas mediante el carné", "Cultura de seguridad", "Activación del plan de emergencia para los riesgos asociados"], v);
const intrusion = hurto;
const paquete = (v: number[]) => crear(["Reporte de actividades subestándar y detección temprana de paquetes sospechosos", "Plan de contingencia", "Cultura de seguridad", "Aseguramiento del área", "Activación del plan de emergencia para los riesgos asociados"], v);
const registros: Registro[] = [
  { consecutivo: "SIM-IB-2026-001", fecha: new Date("2026-01-19T15:00:00.000Z"), tipo: "SIMULACRO HURTO", area: "ALMACÉN", horaInicio: "10:00", supervisor: "Cristian Salgado", resultado: "DETECTADO", aspectos: hurto([3, 1, 3, 3, 3]), conclusion: "Se cumplió el objetivo: el evento fue detectado por el personal administrativo." },
  { consecutivo: "SIM-IB-2026-002", fecha: new Date("2026-02-10T12:00:00.000Z"), tipo: "SIMULACRO PAQUETE SOSPECHOSO", area: "OFICINA DE BIENESTAR", horaInicio: "07:00", supervisor: "Sebastian Yunda Rodriguez", resultado: "DETECTADO", aspectos: paquete([3, 3, 3, 3, 3]), conclusion: "Se registró la ejecución histórica del simulacro de paquete sospechoso y la retroalimentación al personal." },
  { consecutivo: "SIM-IB-2026-003", fecha: new Date("2026-03-09T17:00:00.000Z"), tipo: "SIMULACRO INTRUSION", area: "ARMADO DE RAMOS ESPECIALES", horaInicio: "12:00", supervisor: "Javier Serna Vargas", resultado: "DETECTADO", aspectos: intrusion([3, 3, 3, 3, 3]), conclusion: "El personal conoce los procedimientos de control de acceso e identificación de visitantes o intrusos." },
  { consecutivo: "SIM-IB-2026-004", fecha: new Date("2026-05-26T12:00:00.000Z"), tipo: "SIMULACRO PAQUETE SOSPECHOSO", area: "OFICINA DE NÓMINA", horaInicio: "07:00", supervisor: "Cristian Salgado", resultado: "NO DETECTADO", aspectos: paquete([1, 1, 1, 1, 1]), conclusion: "El personal no tenía claro el procedimiento de manejo de correspondencia y paquete abandonado. Fue subsanado por una ejecución posterior exitosa.", cierrePosterior: "SIM-IB-2026-005" },
  { consecutivo: "SIM-IB-2026-005", fecha: new Date("2026-08-12T11:00:00.000Z"), tipo: "SIMULACRO PAQUETE SOSPECHOSO", area: "OFICINA DE NÓMINA", horaInicio: "06:00", supervisor: "Cristian Salgado", resultado: "DETECTADO", aspectos: paquete([3, 3, 3, 3, 3]), conclusion: "El paquete fue detectado y reportado en el tiempo estimado, aplicando los controles previstos." },
];
function promedio(a: Aspecto[]) { const p: Record<number, number> = { 3: 1, 2: .5, 1: 0 }; return a.reduce((t, x) => t + p[x.calificacion], 0) / a.length; }
async function main() { let importados = 0; for (const r of registros) { if (await prisma.simulacroActividad.findUnique({ where: { consecutivo: r.consecutivo }, select: { id: true } })) continue; const origenId = `HISTORICO-${r.consecutivo}`; if (await prisma.actividadSupervisor.findUnique({ where: { origenId }, select: { id: true } })) continue; await prisma.$transaction(async tx => { const actividad = await tx.actividadSupervisor.create({ data: { origenId, fechaPlaneada: r.fecha, finca: "IB", actividad: r.tipo, area: r.area, supervisorNombre: r.supervisor, estado: "TERMINADO", fechaCierre: r.fecha, cumplidaEnFecha: true, cerradoPor: r.supervisor, observacionesCierre: r.cierrePosterior ? `Cierre histórico validado: resultado subsanado por ejecución posterior exitosa ${r.cierrePosterior}.` : "Histórico cerrado por procedimiento anterior.", creadoPor: "Importación histórica", creadoPorCorreo: "historico@falconservice.local", createdAt: r.fecha } }); await tx.simulacroActividad.create({ data: { actividadId: actividad.id, tipo: r.tipo, finca: "IB", area: r.area, grupoObjeto: `Personal de ${r.area}`, personasInformadas: "Registro histórico importado", escenario: r.area, horaInicio: r.horaInicio, duracionMinutos: 30, consecutivo: r.consecutivo, guion: "Registro histórico importado desde los formatos de simulacro IB 2026.", resultado: r.resultado, cumplimientoObjetivo: r.conclusion, desarrollo: `Simulacro histórico importado desde ${r.consecutivo}.`, pasos: [{ descripcion: `Simulacro histórico importado desde ${r.consecutivo}.` }], aspectos: r.aspectos, promedioEvaluacion: promedio(r.aspectos), conclusion: r.conclusion, requiereSac: false, evidencias: [], creadoPor: r.supervisor, creadoPorCorreo: "historico@falconservice.local", createdAt: r.fecha } }); }); importados++; } console.log(JSON.stringify({ total: registros.length, importados, cierresPorRepeticion: 1 })); }
main().finally(() => prisma.$disconnect());
